apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zlwd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-zlwd@sha256:7f8832c4f15b8f9e28b3f1bab5be65431a001130ff44fac34181ef04443da3c2
        name: my-nodejs
        resources: {}
status: {}
